### ISSUE TITLE
Api.ai help needed

### ISSUE THREAD

**Issue by srobin55** [actions-on-google/dialogflow-facts-about-google-nodejs#15]
After having followed the previous steps as mentioned in the README and YouTube tutorial,
I clicked on "RESTORE from ZIP" and placed the zip file there.

But I got this Errror message:
No intents or entities found in file. Make sure that file is a zip archive and that intents and entities are in json format and are located inside intents and entities folders correspondingly.

**Comment by Canain** [comment]
Are you sure you are uploading the right zip file?
The zip file should be called `FactsAboutGoogle.zip` which is inside the repository.
If you are downloading the repository as a zip itself, you need to extract the repository first and get the zip `FactsAboutGoogle.zip` out of that to upload.

**Comment by Canain** [comment]
Closing this issue since there hasn't been more comments.

Please open another issue if you need more help.
