### ISSUE TITLE
How to deploy action to google cloud?

### ISSUE THREAD

**Issue by alexa-ai** [actions-on-google/dialogflow-facts-about-google-nodejs#2]
Step #6 says "Deploy this action to your preferred hosting environment". More details need to be added here. 

Where to deploy index.js? In google cloud? We can create projects in google cloud,, but not sure where to add index.js which has all the business logic.

**Comment by priyara123** [comment]
where's the webhook logic being handled? I don't see any route for handling webhook post request from API.AI in the index.js. Could you pls add those details?

**Comment by alexa-ai** [comment]
@priyara123 : webhook need to be added under fulfillment section in api.ai agent.

**Comment by embiem** [comment]
There's a tutorial about [how to deploy fulfullment](https://developers.google.com/actions/get-started/deploy-fulfillment).

I personally used the firebase tools, as I find it more convenient than with the actual gcloud tools. 
If you deploy to firebase functions, you will need to change the export in index.js to:

`exports.factsAboutGoogle = functions.https.onRequest((request, response) => {`

And don't forget to import firebase-functions:

`const functions = require('firebase-functions');`

Hope I could help.

**Comment by kshivanku** [comment]
@priyara123 did you resolve the route issue? I have the same confusion.

**Comment by liangjun-jiang** [comment]
I think the readme is not clear about how to deploy to firebase. The steps are more like
1. create a project in firebase.google.com
2. install firebase cli tool  `npm install -g firebase-tools`
3. `cd facets-about-google-code-directory`
4. run `firebase init functions`
5. answer n for all questions about overwriting files but do npm install
6. run `firebase deploy --only functions`
7. once step 6 is finished, terminal console will log something 'https://us-central1-project-1######.cloudfunctions.net/factsAboutGoogle'
8. copy the link from step 7, and paste to api.ai's fulfillment (continue to readme part of this project)

**Comment by Canain** [comment]
We wanted to link to the Firebase function docs for more specific instructions in case Firebase changes the best deployment method in the future so we don't have to keep maintaining it.

Feel free to open a Pull Request to improve the README so we can discuss about it.
