### ISSUE TITLE
Step 3 contains unrealisable step

### ISSUE THREAD

**Issue by bazted** [actions-on-google/dialogflow-facts-about-google-nodejs#23]
Step 3 contains the screenshot which is not actual and intents to actions which nowadays user won't be able to do. 

From CodeLAB: 
<img width="822" alt="screen shot 2018-04-21 at 12 37 37" src="https://user-images.githubusercontent.com/3298703/39083204-10a0fff0-4561-11e8-9559-3d30bfee020d.png">

Screen from INTEGRATIONS tab today. 
<img width="1067" alt="screen shot 2018-04-21 at 12 38 59" src="https://user-images.githubusercontent.com/3298703/39083205-10c1e94a-4561-11e8-961d-3af275f91dde.png">

Please change a description a little bit and update screen or make it more clear via description.

**Comment by lucaswadedavis** [comment]
This actually seems to have been fixed at some point, so I'm closing this Issue.

If you think the resolution is in error, please re-open the issue with fresh information.
