### ISSUE TITLE
importing the project in dialogflow

### ISSUE THREAD

**Issue by vanshajhmadan** [actions-on-google/dialogflow-facts-about-google-nodejs#26]
When importing the project zip file in dialogflow  it was not uploading and a message stating that the files does not have intents and other properties.
![screenshot 40](https://user-images.githubusercontent.com/31125397/39511599-9637517a-4e0b-11e8-8420-b22404b66a9c.png)

**Comment by Fleker** [comment]
Why is your zip called `dialogflow-facts-about-google-nodejs-master.zip`? You should import the `FactsAboutGoogle.zip` which is one of the files in the project.

**Comment by alyeung** [comment]
@vanshajhmadan did you get a resolution?

**Comment by SanaWaseem** [comment]
Any update on this?

**Comment by findzaatar** [comment]
@SanaWaseem @vanshajhmadan 

Closing since the sample has been updated and you'll now be importing agent.zip
