### ISSUE TITLE
Failed to connect to Google Actions when account linking is activated

### ISSUE THREAD

**Issue by AngelLuisSanchez** [actions-on-google/dialogflow-facts-about-google-nodejs#27]
Hi!
I am not able to connect and integrate to Google Actions when I set Auth0 parameters.
I'm following this tutorial but not works to me :(

I want to authenticate the user and know some user's attributes such as email and username.

Before I set Auth0 server, Google Actions works fine (without authentication).
This is the error that Google Actions shows;
"It looks like your my test app account is not linked yet".

What is more, I can't integrate with Google Assistant from DialogFlow.

![image](https://user-images.githubusercontent.com/9683844/40307151-9b67669e-5d01-11e8-9d17-b1388c1f0afb.png)

I use dialogflow V2 and jovo to deploy.

Any idea?

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
