### ISSUE TITLE
DialogFlow with Google OAuth2.0

### ISSUE THREAD

**Issue by aarontanzk** [actions-on-google/dialogflow-facts-about-google-nodejs#28]
Hi any sample code that uses DialogFlow with Google OAuth2.0?

I believe there should be an oauthcallback and token endpoints but I can't seem to find any code to use.

This is for the account linking authorisation url and token url.

**Comment by findzaatar** [comment]
Here's an example of what you'd have inside your index.js for auth for specific APIs: 
```
const {google} = require('googleapis');
const sheets = google.sheets('v4');
const serviceAccount =  { };   // Enter Service Account private key JSON

const client = new google.auth.JWT({
  email: serviceAccount.client_email,
  key: serviceAccount.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.file']
});
```

<img width="922" alt="screen shot 2019-02-15 at 12 29 38 pm" src="https://user-images.githubusercontent.com/11345614/52882710-6d5af180-311d-11e9-950b-61fcfc7d0a25.png">

Also, the Actions on Google docs go further into detail on [OAuth2.0 and Account linking](https://developers.google.com/actions/identity/oauth2).
