### ISSUE TITLE
Step 7: Restore from Zip - No intents or entities found in file

### ISSUE THREAD

**Issue by alyeung** [actions-on-google/dialogflow-facts-about-google-nodejs#29]
Hello @chatasweetie  & team:

1. I downloaded this, https://github.com/actions-on-google/dialogflow-facts-about-google-nodejs/blob/master/FactsAboutGoogle.zip
2. Saved the file to downloads on my local machine.
3. Tried to use the restore from zip button as instructed in step 7 of the Upload Agent within Dialogflow
4. No intents or entities found in a file (see image): "No intents or entities found in file. Make sure that file is a zip archive and that intents and entities are in json format and are located inside intents and entities folders correspondingly."
5. Tried to unzip the .zip file to inspect, but was unable to.
6. I am using Chrome: 67.0.3396.99 (Official Build) (64-bit) on Windows 10 Pro V 1709

Is the zip created by zipping the functions folder? https://github.com/actions-on-google/dialogflow-facts-about-google-nodejs/tree/master/functions

Thanks,

Allan

![image](https://user-images.githubusercontent.com/4118083/42469166-cc79ba94-836b-11e8-8c2a-adc9e93602a0.png)

**Comment by Canain** [comment]
The link you posted links to an html file showing the [GitHub page](https://github.com/actions-on-google/dialogflow-facts-about-google-nodejs/blob/master/FactsAboutGoogle.zip) for that file.

Try downloading it using `?raw=true` in url like: https://github.com/actions-on-google/dialogflow-facts-about-google-nodejs/blob/master/FactsAboutGoogle.zip?raw=true

**Comment by alyeung** [comment]
Hello @Canain - thank you for your quick response.

your suggestion resolved the issue.  I appreciate the help.

**Comment by Canain** [comment]
Glad you resolve your issue!
