### ISSUE TITLE
Using app.data [QUESTION]

### ISSUE THREAD

**Issue by embiem** [actions-on-google/dialogflow-facts-about-google-nodejs#5]
Hey!

I have one question about the usage of `app.data`. This app uses it to save the history and hq facts and delete them once they're told.

Is this a special property of the ApiAiApp class? Is it temporary or actually stored between sessions? 

I use firebase functions and the app object is actually created inside of the function. So how is it that the app.data property lives between multiple requests?

Any pointers to resources about the lifecycle of firebase functions would be appreciated as well.

**Comment by liangjun-jiang** [comment]
For each request, an instance of cloud function is created. Each request is independent.

**Comment by embiem** [comment]
@loftyet and how is it possible that app.data persists between calls?

**Comment by smishra2** [comment]
In the ApiAiApp class, app.data uses API.AI contexts to store data between requests. 

https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/api-ai-app.js#L1388

**Comment by embiem** [comment]
thank you very much for clarifying!!

**Comment by joramantwi** [comment]
I need help with the same thing. O::::: the link is deleted
