### ISSUE TITLE
when i tried to launch it in gcloud got the below error 

### ISSUE THREAD

**Issue by maikeffi** [actions-on-google/dialogflow-facts-about-google-nodejs#6]
> facts-about-google@0.0.1 start /app
> functions deploy factsAboutGoogle --trigger-http

sh: 1: functions: not found

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! facts-about-google@0.0.1 start: `functions deploy factsAboutGoogle --trigger-http`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the facts-about-google@0.0.1 start script 'functions deploy factsAboutGoogle --trigger-http'.
npm ERR! This is most likely a problem with the facts-about-google package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     functions deploy factsAboutGoogle --trigger-http
npm ERR! You can get their info via:
npm ERR!     npm owner ls facts-about-google
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by maikeffi** [comment]
When i tried to run locally ! Got the below error 

D:\Code\Node js\apiai-facts-about-google-nodejs>functions deploy factsAboutGoogle --trigger-http
Warning: You're using Node.js v6.10.3 but Google Cloud Functions only supports v6.9.1.
ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exists? Is there a syntax error in your code?
ERROR: Detailed stack trace: module.js:471
    throw err;
    ^

Error: Cannot find module 'actions-on-google'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Code\Node js\apiai-facts-about-google-nodejs\index.js:17:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

ERROR: Error: Failed to deploy function.
    at exec (C:\Users\kannan\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\src\cli\controller.js:135:18)
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by smishra2** [comment]
Hi @maikeffi for this issue try installing the [Google Cloud Functions Emulator](https://cloud.google.com/functions/docs/emulator). Keep in mind the sample has been updated for [Cloud Functions for Firebase](https://firebase.google.com/docs/functions/)

**Comment by nikitsharma15** [comment]
@maikeffi Try to deploy it by using firebase just follow these steps:

( Make sure you've properly installed other tools like node, npm and etc )
1. Go to your working directory 
2. Open terminal and type npm install ( This will install dependencies for your project )
3. Install firebase tools by typing " npm install -g firebase-tools " ( without quotes ) ( This installs the globally available firebase command )
4. After that type firebase login (This will authenticate the firebase tools just follow the screen instructions carefully )
5. After that type firebase use --add ( This command allows you to select a Firebase project and give it a named alias.)
6. After that firebase use project-id ( For this go to firebase console then click on project settings then you'll see your app project id
7. After that type firebase deploy ( It will take some time hardly 5 minutes depends on your internet connection )
8. After successfully done go to Api.ai, click on fullfilment section then enable webhook, paste your Function URL and you're done. 

Hope this will help you :)

**Comment by Canain** [comment]
Closing this issue since we now use Firebase Functions and there hasn't been more comments on this issue.

Please open another issue if you have problems with Firebase Functions.
